### PR TITLE
rewrite for guzzle 7 and php 7.3+

### PR DESCRIPTION
**Pull request by AnssiAhola**
Hi @ricbra 
I saw the issue #55 and seeing its from 2019 and no PR working on it, I thought might as well contribute my work on this on my local clone.

Done:
- Updated syntax to php 7.3+
- bumped versions on php(>=7.3.0), Guzzle(~7.0), Guzzle Services(~1.2.0),Oauth Subscriber(~0.4) and phpunit(~9.5), havent tested minimum versions
- updated tests to be Guzzle 7.0 compatible
- changed fixtures to .json to support new `MockHandler` Response, no longer support string as a response
- Updated `ThrottleSubscriber` and `ThrottleSubscriberTest`

To Do:
- Other tests pass, but could use some more 'real world' testing
- Update README.md properly

Hope this repo isnt abandoned. 😅

### CODE REVIEW

**Comment by froschdesign** [comment]
@AnssiAhola 
I would suggest you stay on topic. No change of code styling and no new features. This can be done in separate pull requests.

**Comment by AnssiAhola** [comment]
> 
> 
> @AnssiAhola
> I would suggest you stay on topic. No change of code styling and no new features. This can be done in separate pull requests.

Fair enough, what do you mean specifically with "change of code styling"

**Comment by alruddick** [comment]
Has this PR been abandoned? I need a PHP7.2+ client for Discogs so this would be ideal

**Comment by AnssiAhola** [comment]
> Has this PR been abandoned? I need a PHP7.2+ client for Discogs so this would be ideal

Theres a fork thats maintained and available via packagist here https://github.com/calliostro/php-discogs-api

**Comment by ricbra** [comment]
Cool didn't knew there were maintained forks. Gonna archive this repo and will point to the fork instead.

**Pull request closed without merging**
