### PR TITLE
Changed baseURL to HTTPS

### PR DESCRIPTION
**Pull request by davalb**

### CODE REVIEW

**Comment by ricbra** [comment]
Could you also fix all tests? :smile:

**Comment by davalb** [comment]
oh, of course. Done. Please check line 186 of ClientTest. Not sure if I got that right.

**Comment by ricbra** [comment]
Thanks for the work @davalb , looks perfectly fine to me.

**Comment by davalb** [comment]
thanks, @ricbra. Do you plan to release a new version of this api on packagist?

**Comment by ricbra** [comment]
@davalb Just tagged 1.2.0.

**Pull request merged**
